
[functions.email-webhook-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/email-webhook-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/email-webhook-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/email-webhook-proxy/*.html" ]

[functions.handle-gmail-oauth-callback]
enabled = true
verify_jwt = true
import_map = "./functions/handle-gmail-oauth-callback/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/handle-gmail-oauth-callback/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/handle-gmail-oauth-callback/*.html" ]
